// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScoutPlatform.Infrastructure.Persistence;

#nullable disable

namespace ScoutPlatform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ScoutPlatformDbContext))]
    partial class ScoutPlatformDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScoutPlatform.Infrastructure.Persistence.Entities.MetricDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Group")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("HigherIsBetter")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("MaxExpected")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("MinExpected")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizationStrategy")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Unit")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("MetricDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f37f1d1-6433-4f4b-b57d-47b503c9d101"),
                            CreatedAtUtc = new DateTime(2026, 3, 2, 18, 5, 42, 191, DateTimeKind.Utc).AddTicks(2836),
                            Description = "Expected goals per 90 minutes",
                            Group = "Attacking",
                            HigherIsBetter = true,
                            Key = "xg_per90",
                            MaxExpected = 0.60m,
                            MinExpected = 0.05m,
                            Name = "xG Per 90",
                            NormalizationStrategy = "MinMax",
                            Unit = "xG"
                        },
                        new
                        {
                            Id = new Guid("9f37f1d1-6433-4f4b-b57d-47b503c9d102"),
                            CreatedAtUtc = new DateTime(2026, 3, 2, 18, 5, 42, 191, DateTimeKind.Utc).AddTicks(2860),
                            Description = "Pressuring actions per 90 minutes",
                            Group = "Defending",
                            HigherIsBetter = true,
                            Key = "pressures_per90",
                            MaxExpected = 25m,
                            MinExpected = 5m,
                            Name = "Pressures Per 90",
                            NormalizationStrategy = "MinMax",
                            Unit = "count"
                        },
                        new
                        {
                            Id = new Guid("9f37f1d1-6433-4f4b-b57d-47b503c9d103"),
                            CreatedAtUtc = new DateTime(2026, 3, 2, 18, 5, 42, 191, DateTimeKind.Utc).AddTicks(2867),
                            Description = "Minutes played in season",
                            Group = "Availability",
                            HigherIsBetter = true,
                            Key = "minutes",
                            MaxExpected = 3200m,
                            MinExpected = 0m,
                            Name = "Minutes Played",
                            NormalizationStrategy = "MinMax",
                            Unit = "minutes"
                        });
                });

            modelBuilder.Entity("ScoutPlatform.Infrastructure.Persistence.Entities.PlayerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentClub")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("MarketValueEur")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PrimaryPosition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("ScoutPlatform.Infrastructure.Persistence.Entities.PlayerMetricEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompetitionId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal?>("Minutes")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "SeasonId", "MetricKey");

                    b.ToTable("PlayerMetrics", (string)null);
                });

            modelBuilder.Entity("ScoutPlatform.Infrastructure.Persistence.Entities.SuitabilityScoreEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BreakdownJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CalculatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Score")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<int>("ScoreVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TeamProfileId", "PlayerId", "ScoreVersion");

                    b.ToTable("SuitabilityScores", (string)null);
                });

            modelBuilder.Entity("ScoutPlatform.Infrastructure.Persistence.Entities.TeamProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BudgetMaxEur")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MinMinutesPlayed")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("TargetPosition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("TeamProfiles", (string)null);
                });

            modelBuilder.Entity("ScoutPlatform.Infrastructure.Persistence.Entities.TeamProfileWeightEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsHardConstraint")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal?>("MinValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("TeamProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("TeamProfileId", "MetricKey")
                        .IsUnique();

                    b.ToTable("TeamProfileWeights", (string)null);
                });

            modelBuilder.Entity("ScoutPlatform.Infrastructure.Persistence.Entities.PlayerMetricEntity", b =>
                {
                    b.HasOne("ScoutPlatform.Infrastructure.Persistence.Entities.PlayerEntity", "Player")
                        .WithMany("Metrics")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ScoutPlatform.Infrastructure.Persistence.Entities.TeamProfileWeightEntity", b =>
                {
                    b.HasOne("ScoutPlatform.Infrastructure.Persistence.Entities.TeamProfileEntity", "TeamProfile")
                        .WithMany("Weights")
                        .HasForeignKey("TeamProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamProfile");
                });

            modelBuilder.Entity("ScoutPlatform.Infrastructure.Persistence.Entities.PlayerEntity", b =>
                {
                    b.Navigation("Metrics");
                });

            modelBuilder.Entity("ScoutPlatform.Infrastructure.Persistence.Entities.TeamProfileEntity", b =>
                {
                    b.Navigation("Weights");
                });
#pragma warning restore 612, 618
        }
    }
}
